language: ruby
cache: bundler
rvm:
  - 2.6.3
addons:
  apt:
    packages:
      - openjdk-8-jre
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec jekyll clean && bundle exec jekyll build
branches:
  only:
    - source
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  target-branch: master 
  on:
    branch: source
